name = "TableOne"
uuid = "d36ae967-72a8-4ff4-a661-f51e671fe83a"
authors = ["Mark Pritchard <mark.pritchard@ndm.ox.ac.uk>"]
version = "0.2.5"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"

[extensions]
TableOneCategoricalVariables = "CategoricalArrays"

[compat]
CategoricalArrays = "0.8, 0.9, 0.10, 1"
DataFrames = "1"
HypothesisTests = "0.11.4"
PackageExtensionCompat = "1"
StatsBase = "0.33, 0.34"
julia = "1.6"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
docs = ["CategoricalArrays", "Documenter", "RDatasets", "StableRNGs"]
test = ["CategoricalArrays", "Documenter", "RDatasets", "StableRNGs", "Test"]
